### ISSUE TITLE
Request timeout/Invalid password

### ISSUE THREAD

**Issue by trmendes** [torhve/weechat-matrix-protocol-script#113]
```
matrix: Connecting to homeserver URL: https://matrix.org/
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
request:
  url: https://matrix.org/_matrix/client/r0/login
  post:
    postfields: {"password":"my_password","type":"m.login.password","user":"my_user",
"initial_device_display_name":"WeeMatrix"}
    accept_encoding: application/json
    header: 1
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
reply:
  rc: -2
  command: url:https://matrix.org/_matrix/client/r0/login
  extra:
  stdout:
  stderr:
Call to API errored in command url:https://matrix.org/_matrix/client/r0/login, maybe timeout?
```

This is all I get from Weechat-Matrix

I'm on archlinux, weechat version 2.1, lua 5.3.4, lua-cjson 2.1.0-3

**Comment by trmendes** [comment]
```
request:
  post:
    accept_encoding: application/json
    header: 1
    postfields:
{"password":"my_password","type":"m.login.password","user":"my_email","initial_device_display_name":"WeeMatrix"}
  url: https://matrix.org/_matrix/client/r0/login
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
reply:
  rc: 0
  extra:
  stderr:
  stdout: HTTP/1.1 403 Forbidden
Date: Mon, 07 May 2018 10:53:53 GMT
Content-Type: application/json
Content-Length: 52
Connection: keep-alive
Set-Cookie: __cfduid=xxxxxxxxxxxxxx; expires=Tue, 07-May-19 10:53:52 GMT; path=/; domain=.matrix.org; HttpOnly
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Cache-Control: no-cache, no-store, must-revalidate
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 417325319afc4b51-GRU

{"errcode":"M_FORBIDDEN","error":"Invalid password"}
  command: url:https://matrix.org/_matrix/client/r0/login
matrix: Error code during login: Invalid password, code: M_FORBIDDEN
matrix: Please verify your username and password
```

It says 

```
{"errcode":"M_FORBIDDEN","error":"Invalid password"}
  command: url:https://matrix.org/_matrix/client/r0/login
matrix: Error code during login: Invalid password, code: M_FORBIDDEN
```

But I'm pretty sure my password isn't wrong.

Any help?

**Comment by HauctoPuce** [comment]
I have the same problem here with archlinux and same versions. Update and reload doesn't change the error message.

**Comment by ElonSatoshi** [comment]
I also have the same error, except on Parabola. Same versions. Update and reload doesn't change it for me. My homeserver is disroot.org.

Also, how do I get the extra data you guys are pasting? All I see is:

```
matrix: Connecting to homeserver URL: https://disroot.org/
Call to API errored in command url:https://disroot.org/_matrix/client/r0/login, maybe timeout?
```

**Comment by trmendes** [comment]
@ElonSatoshi if you edit the lua file from the script you will see a DEBUG variable (line 68 for the last file version I guess). Change its value to true if it is false, save it and reload the plugin.

**Comment by trmendes** [comment]
@HauctoPuce, @ElonSatoshi 

I've fixed it here. Not sure if I'm doing it the best way so I'm going to submit a pull request to the project to check if I'm right or wrong. I hope I'm right so we all can access Matrix using Weechat soon \o/

**Comment by ElonSatoshi** [comment]
I'm still getting this error. I noticed you added a commit to test whether the username was an email address or an ID, so I tried changing my user to my full ID instead of just... my username. But I still got the same error. I enabled debug mode so here's some sweet, sweet output for you guys:

```
08:43 matrix: Unable to load olm encryption library. Not enabling encryption. Please see documentation (README.md) for information on how to enable.
08:43 matrix: Connecting to homeserver URL: https://disroot.org/
08:43 =!= - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
08:43 request: 
08:43   post: 
08:43     postfields: {"identifier.medium":"user","identifier.address":"elonsatoshi","password":"dQw4w9WgXcQ","initial_device_display_name":"WeeMatrix","user":"elonsatoshi","identifier.type":"m.id.thirdparty","medium":"user","type":"m.login.password"}
08:43     accept_encoding: application/json
08:43     header: 1
08:43   url: https://disroot.org/_matrix/client/r0/login
08:44 =!= - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
08:44 reply: 
08:44   rc: -2
08:44   extra: 
08:44   command: url:https://disroot.org/_matrix/client/r0/login
08:44   stdout: 
08:44   stderr: 
08:44 =!= Call to API errored in command url:https://disroot.org/_matrix/client/r0/login, maybe timeout?

08:48 matrix: Unable to load olm encryption library. Not enabling encryption. Please see documentation (README.md) for information on how to enable.
08:48 matrix: Connecting to homeserver URL: https://disroot.org/
08:48 =!= - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
08:48 request: 
08:48   url: https://disroot.org/_matrix/client/r0/login
08:48   post: 
08:48     accept_encoding: application/json
08:48     header: 1
08:48     postfields: {"user":"@elonsatoshi:disroot.org","type":"m.login.password","initial_device_display_name":"WeeMatrix","identifier.type":"m.id.thirdparty","identifier.medium":"user","password":"dQw4w9WgXcQ","identifier.address":"@elonsatoshi:disroot.org","medium":"user"}
08:48 =!= - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
08:48 reply: 
08:48   command: url:https://disroot.org/_matrix/client/r0/login
08:48   rc: -2
08:48   stderr: 
08:48   extra: 
08:48   stdout: 
08:48 =!= Call to API errored in command url:https://disroot.org/_matrix/client/r0/login, maybe timeout?
```

**Comment by trmendes** [comment]
@ElonSatoshi I still getting this message most of the times I try to connect to Matrix using weechat + plugin. But then it seems to be a timeout for real or something else!!

Btw...I strongly suggest you to remove you message because your login and password are there! I would also change it as soon as possible too.

**Comment by ElonSatoshi** [comment]
Lol that's not my password, that's the Youtube ID for Rick Astley's Never Gonna Give You Up! And I'm okay with my Matrix ID being public, I'd be flattered if you messaged me there, although I'd be using Riot and not WeeMatrix for the moment.

**Comment by trmendes** [comment]
@ElonSatoshi That is awesome :)...I'm still using Riot here too but I miss weechat and the terminal. As soon as I have more time  I'll try to have a look why it still, most of time, falling to login.

**Comment by proycon** [comment]
I seem to be running into this same issue currently, guess it should be reopened?

```
Call to API errored in command url:https://matrix.org:8448/_matrix/client/r0/login, maybe timeout?
```

**Comment by proycon** [comment]
(Actually, I removed the :8448 in the homeserver settings and things do seem to work now)
